extends:
  - standard
  - prettier
  - prettier/standard
plugins:
  - node
  - mocha
env:
  jest: true
  mocha: true
rules:
  no-debugger: off
  no-var: error
  prefer-const: error
  node/no-missing-require: error
