extends: standard
plugins:
  - node
  - mocha
env:
  mocha: true
# テスト用のグローバル変数 # TODO: 自動的にglobalを認識させたい
globals:
  assert: true
  goqoo: true
rules:
  comma-dangle:
    - error
    - only-multiline
  no-debugger: off
  no-var: error
  prefer-const: error
  node/no-missing-require: error
